name: Trigger auto deployment for ssh

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [master]
    paths:
      - "**"
      - ".github/workflows/ssh-AutoDeployTrigger-26fe26f8-f1d4-48ca-a1bc-1913914db33b.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SSH_AZURE_CREDENTIALS }}

      - name: Replace CUSTOM_HEADER in nginx.conf
        run: |
          sed -i 's/CUSTOM_HEADER/${{ secrets.CUSTOM_HEADER }}/g' nginx/nginx.conf

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/
          dockerfilePath: ./nginx/Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.SSH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SSH_REGISTRY_PASSWORD }}
          containerAppName: ssh
          resourceGroup: k3sphere
          imageToBuild: jasonhao123/ssh:${{ github.sha }}
